apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-1
spec:
  # initContainers:
  # - name: contenedor
  #   image: k8s.gcr.io/busybox
  #   command: [ "/bin/sh", "-c", "rm -f /tmp/tls.crt" ]
  #   volumeMounts:
  #     - name: volume-secret-example
  #       mountPath: /tmp/

  containers:
    - name: contenedor1
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "sleep 1000000" ]
      envFrom:
      - secretRef:
          name: secret-1
      env:
      - name: VERSION
        valueFrom:
          secretKeyRef:
            name: secret-2
            key: usu2-pass
        
      volumeMounts:
        - name: volume-secret-example
          mountPath: /etc/certificates
          readOnly: true
  volumes:
    - name: volume-secret-example
      secret:
        secretName: secret-tls
        optional: false
