apiVersion: v1
kind: Secret
metadata:
  name: secret-tiger-docker
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |-
  {
    "auths":{
        "https://index.docker.io/v1/":{
          "username":"tiger",
          "password":"pass113",
          "email":"tiger@acme.com",
          "auth":"dGlnZXI6cGFzczExMw=="
        }
    }
  }