apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
    - name: test-container
      image: ubuntu
      command: [ "/bin/sh", "-c", "sleep 1000000" ]
      env:
      - name: DATOS
        valueFrom:
          secretKeyRef:
            name: datos
            key: myfile.env
  restartPolicy: Never
