apiVersion: v1
kind: Secret
metadata:
  name: secret-dockercfg
type: kubernetes.io/dockercfg
data:
  .dockercfg: |
        "<base64 encoded ~/.dockercfg file>"

# kubectl create secret docker-registry secret-tiger-docker \
#   --docker-username=tiger \
#   --docker-password=pass113 \
#   --docker-email=tiger@acme.com \
#   --docker-server=my-registry.example:5000