apiVersion: v1
kind: Pod
metadata:
  name: pod-env-1
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: mypassword
    - name: nombre_pod
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: myenv
      value: example
    volumeMounts: # aquí se anexa un volume en alguna ruta del container
    - mountPath: /usr/share/nginx/
      name: temp

  volumes: 
  - name: temp
    emptyDir: {}