apiVersion: v1
kind: Pod
metadata:
  name: mypod-2
  labels:
    app: example
    version: v1
spec:
  containers:
  - name: hello
    image: "gcr.io/google-samples/hello-app:1.0" #2.0" # funciona en el 8080
    ports:
    - containerPort: 8080
    readinessProbe:
        httpGet:
          path: / # puede ser solo la raiz "/", probar esto en caso no funcione en azure application gateway
          port: 8080
        initialDelaySeconds: 30
        timeoutSeconds: 5
        periodSeconds: 5