apiVersion: v1
kind: Service
metadata:
  name: my-cip-service
  namespace: default
  labels:
    app: example # secelctor que puscara este label en los pods 
spec:
  type: ClusterIP #NodePort, LoadBalancer, ExternalName, None (headless)
  selector:
    app: example
    #version: v1 # si no quiero buscar versiones 
  ports:
  - port: 80 # obligatorio
    #protocol: TCP
    targetPort: 8080 # puertos que usan los pods
    name: http-8080 # no es necesario si son los mismos pods 
    # name: http-appmetrics# <protocol>[-<suffix>].
    # appProtocol: http # <protocol>
    # nodePort: 32225 #<30000 - 3XYZAC>

# <service-name>.<namespace>.svc.cluster.local

# kubectl exec -it pod-name -- sh
# apk add --no-cache curl
# curl cluster-ip:80
# -> cluster-ip es el valor de clusterIP en tu servicio.