apiVersion: v1
kind: Pod
metadata:
  name: pod-vol-2
spec:

  nodeSelector:
    node: system #workloads

  volumes:
  - name: shared-data
    hostPath:
      path: /home/myfolder
    #emptyDir: {} # probar con hostpath y desplegar el pod en diferentes nodos y ve que sucede

  containers:
  - name: nginx
    image: nginx:alpine
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
      readOnly: true

  - name: busybox
    image: busybox
    command:
      - sleep
      - "3600"
    volumeMounts:
    - name: shared-data
      mountPath: /pod-data