apiVersion: v1
kind: Service
metadata:
  name: my-lb-service
spec:
  type: LoadBalancer
  selector:
    app: example
    # version: v1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080 # puertos que usan los pods
    name: http-8080
  # - protocol: TCP
  #   port: 443
  #   targetPort: 8443 # puertos que usan los pods
  #   name: https-8443

# kubectl exec -it pod-name -- sh
# apk add --no-cache curl
# curl cluster-ip:<port>
# curl cluster-ip.<namespace>:<port>
# curl cluster-ip.<namespace>.svc.cluster.local:<port>
# -> cluster-ip es el valor de clusterIP en tu servicio.