apiVersion: v1
kind: Pod
metadata:
  name: apiecho-2
  labels:
    app: apiecho-2
spec:
  nodeSelector:
    kubernetes.io/hostname: k3d-mycluster-agent-2
    # kubernetes.io/hostname: gke-mygke-cluster-workloads-4e825ce5-mh5m
  containers:
   - name: api
     image: wjma90/api-echo-example
     env:
      - name: TARGET_HOST
        value: http://10.42.3.6:8080/ # aqui va la ip del pod que consumiremos (api echo 1)
     ports:
        - containerPort: 8080
