#este pod termina mal con exit 1 y por ende el estado es Error
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  nodeSelector:
    node: workloads
  containers:
  - name: myapp-container
    image: busybox
    imagePullPolicy: IfNotPresent
    command: ['sh', '-c', 'echo The Pod is running && sleep 30 && exit 1']
  restartPolicy: OnFailure