apiVersion: v1
kind: Pod
metadata:
  name: nginx2
  namespace: api
  labels:
    app: nginx2
    tier: frontend
spec:
  containers:
   - name: nginx
     image: nginx:latest
     ports:
        - containerPort: 80
