apiVersion: v1
kind: LimitRange
metadata:
  name: limits
  namespace: api
spec:
  limits:
  - default:
      memory: 512Mi
      cpu: 0.6
    defaultRequest:
      memory: 256Mi
      cpu: 0.4
    max:
      memory: 1Gi
      cpu: 1
    min:
      memory: 128Mi
      cpu: 0.3
    type: Container # puede ser Pod

# see -> https://github.com/kubernetes/community/blob/master/contributors/design-proposals/resource-management/admission_control_limit_range.md
