apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: mycluster
image: rancher/k3s:v1.25.13-rc3-k3s1 # v1.24.14-rc1-k3s1 # v1.22.17-k3s1
servers: 1
agents: 4
ports:
 - port: 80:80 # http
   nodeFilters:
   - loadbalancer
 - port: 443:443 # https
   nodeFilters:
   - loadbalancer
 - port: 9090:9090 #prometheus
   nodeFilters:
   - loadbalancer
 - port: 20001:20001 #kiali
   nodeFilters:
   - loadbalancer
 - port: 16686:16686 #jaeger
   nodeFilters:
   - loadbalancer
 - port: 3000:3000 #grafana
   nodeFilters:
   - loadbalancer
options:
 k3d: 
   wait: true 
   timeout: "60s"
   disableLoadbalancer: false
 k3s:
   extraArgs:
  #  - arg: --disable=traefik
  #    nodeFilters:
  #    - server:*
  #  - arg: --disable-network-policy
  #    nodeFilters:
  #    - server:*
  #  - arg: --flannel-backend=none
  #    nodeFilters:
  #    - server:*
   - arg: --tls-san=my.host.domain
     nodeFilters:
     - server:*
   nodeLabels:
   - label: node=system
     nodeFilters:
     - agent:0
   - label: node=system
     nodeFilters:
     - agent:1
   - label: node=workloads
     nodeFilters:
     - agent:2
   - label: node=workloads
     nodeFilters:
     - agent:3
 kubeconfig:
   updateDefaultKubeconfig: true
   switchCurrentContext: true