version: "2"
services:

  tools:
    # build:
    #   context: ./
    #   dockerfile: Dockerfile
    image: rruales06/testdevtools # nick-docker/nombre-imagen
    user: root
    init: true 
    privileged: true
    environment:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
    volumes:
      - ..:/workspace:cached
      - bashhistory:/commandhistory
    command: sleep infinity
    network_mode: host
    extra_hosts:
      - "moby:127.0.0.1"

volumes:
  bashhistory: